### ISSUE TITLE
Failure during crawling

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/spacebox-crawler#4]
Crawler occasionally fails with same error. 
```
3:52PM INF Parse block № 8854486 cmp=worker worker_number=6
3:52PM INF enqueueing new block with height: 14243091 cmp=worker height=14243091
3:52PM INF Parse block № 8854490 cmp=worker worker_number=5
3:52PM INF Parse block № 8854492 cmp=worker worker_number=38
3:52PM INF Parse block № 8854491 cmp=worker worker_number=31
3:52PM INF Parse block № 8854493 cmp=worker worker_number=40
3:52PM INF Parse block № 8854494 cmp=worker worker_number=9
3:52PM INF Parse block № 8854495 cmp=worker worker_number=42
3:52PM INF Parse block № 8854496 cmp=worker worker_number=11
3:52PM INF Parse block № 8854497 cmp=worker worker_number=41
3:52PM INF Parse block № 8854499 cmp=worker worker_number=15
3:52PM INF Parse block № 8854500 cmp=worker worker_number=13
3:52PM INF Parse block № 8854501 cmp=worker worker_number=37
3:52PM INF Parse block № 8854498 cmp=worker worker_number=18
3:52PM INF Parse block № 8854502 cmp=worker worker_number=28
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16c069e]

goroutine 294 [running]:
github.com/bro-n-bro/spacebox-crawler/types.NewTxsFromTmTxs({0xc00db38140, 0x8, 0x3876d20?}, {0x2995220, 0xc0005cdc50})
	/go/src/github.com/spacebox-crawler/types/cosmos.go:88 +0xfe
github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).processHeight(0xc000035ef0, {0x298a6e0, 0xc0001bcac0}, 0x30)
	/go/src/github.com/spacebox-crawler/pkg/worker/process.go:139 +0xc1d
created by github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).Start
	/go/src/github.com/spacebox-crawler/pkg/worker/worker.go:109 +0x28c
```

**Comment by altbro** [comment]
resolved in latest version
