### ISSUE TITLE
Crawler fails with index out of range

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/spacebox-crawler#73]
After restart of docker container, v0.0.11
![image](https://github.com/bro-n-bro/spacebox-crawler/assets/89856346/6c8d4197-712a-43bb-9bf3-f391af96ee32)

```
10:30PM DBG Get txs info block_height=15716839 cmp=worker txs_dur=199.679892 worker_number=23
10:30PM DBG Get validators info block_height=12769844 cmp=worker get_block_events_dur=429.19822 worker_number=21
panic: runtime error: index out of range [0] with length 0

goroutine 1387687 [running]:
github.com/bro-n-bro/spacebox-crawler/modules/gov.(*Module).handlerMsgVoteWeighted(0xc0006153e0, {0x29a0f00, 0xc011ca8c40}, 0xc01b00ad80, 0x0, 0xc0058a83f0)
	/go/src/github.com/spacebox-crawler/modules/gov/message.go:201 +0x535
github.com/bro-n-bro/spacebox-crawler/modules/gov.(*Module).HandleMessage(0xc000f3d7c0?, {0x29a0f00?, 0xc011ca8c40?}, 0x0?, {0x29a2ac0?, 0xc0058a83f0?}, 0xc01b00ad80?)
	/go/src/github.com/spacebox-crawler/modules/gov/message.go:36 +0x77
github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).processMessages(0xc00108e1e0, {0x29a0f00, 0xc011ca8c40}, {0xc01b00ad60, 0x4, 0x2?})
	/go/src/github.com/spacebox-crawler/pkg/worker/process.go:293 +0x49f
github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).processHeight.func8.1()
	/go/src/github.com/spacebox-crawler/pkg/worker/process.go:187 +0x34
github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).withMetrics(0xc000180840?, {0x1f9c1b3?, 0x2?}, 0x0?)
	/go/src/github.com/spacebox-crawler/pkg/worker/metrics.go:9 +0x163
github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).processHeight.func8()
	/go/src/github.com/spacebox-crawler/pkg/worker/process.go:186 +0x75
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220929204114-8fcdb60fdcc0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220929204114-8fcdb60fdcc0/errgroup/errgroup.go:72 +0xa5
```

**Comment by altbro** [comment]
One more fail on different block 
```
7:07AM DBG Get validators info block_height=13381424 cmp=worker get_block_events_dur=930.123162 worker_number=6
panic: runtime error: index out of range [0] with length 0

goroutine 1728196 [running]:
github.com/bro-n-bro/spacebox-crawler/modules/gov.(*Module).handlerMsgVoteWeighted(0xc0000f5980, {0x29a0f00, 0xc0089d1bc0}, 0xc013f09aa0, 0x0, 0xc01e70e1e0)
	/go/src/github.com/spacebox-crawler/modules/gov/message.go:201 +0x535
github.com/bro-n-bro/spacebox-crawler/modules/gov.(*Module).HandleMessage(0xc00057b2c0?, {0x29a0f00?, 0xc0089d1bc0?}, 0x0?, {0x29a2ac0?, 0xc01e70e1e0?}, 0xc013f09aa0?)
	/go/src/github.com/spacebox-crawler/modules/gov/message.go:36 +0x77
github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).processMessages(0xc000d1f950, {0x29a0f00, 0xc0089d1bc0}, {0xc013f09a80, 0x4, 0x0?})
	/go/src/github.com/spacebox-crawler/pkg/worker/process.go:293 +0x49f
github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).processHeight.func8.1()
	/go/src/github.com/spacebox-crawler/pkg/worker/process.go:187 +0x34
github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).withMetrics(0xc028160618?, {0x1f9c1b3?, 0x0?}, 0x0?)
	/go/src/github.com/spacebox-crawler/pkg/worker/metrics.go:9 +0x163
github.com/bro-n-bro/spacebox-crawler/pkg/worker.(*Worker).processHeight.func8()
	/go/src/github.com/spacebox-crawler/pkg/worker/process.go:186 +0x75
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220929204114-8fcdb60fdcc0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220929204114-8fcdb60fdcc0/errgroup/errgroup.go:72 +0xa5

```
